#SUBSTRING 사용
SELECT ANIMAL_ID,NAME,SUBSTRING(DATETIME,1,10)
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

#DATE_FORMAT 사용
SELECT ANIMAL_ID,NAME,DATE_FORMAT(DATETIME,'%Y-%m-%d')
FROM ANIMAL_INS
ORDER BY ANIMAL_ID
