SELECT INS.ANIMAL_ID,INS.ANIMAL_TYPE,INS.NAME
FROM ANIMAL_INS AS INS
LEFT JOIN ANIMAL_OUTS AS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE NOT OUTS.ANIMAL_ID IS NULL 
AND INS.SEX_UPON_INTAKE LIKE '%Intact%' 
AND NOT OUTS.SEX_UPON_OUTCOME LIKE '%Intact%'
ORDER BY INS.ANIMAL_ID
