SELECT ANIMAL_ID,NAME,IF(ANIMAL_ID IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%Neutered%' OR SEX_UPON_INTAKE LIKE '%Spayed%'
),'O','X')
FROM ANIMAL_INS
ORDER BY ANIMAL_ID
